### ISSUE TITLE
文本框组件 鼠标悬浮是“小手状”，不是之前的“文本选择”了

### ISSUE THREAD

**Issue by springmarker** [zdhxiong/mdui#120]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
---------------------------
* 使用平台：Windows10 
* 浏览器及版本：Chrome 62

文本框组件 鼠标悬浮是“小手状”，不是之前的“文本选择”了，是故意这样的，还是BUG

**Comment by zdhxiong** [comment]
Material Design 规范是“小手状”

想改回“文本选择”的话自己加点 CSS：
```css
.mdui-textfield-input:hover {
    cursor: auto !important;
}
```

![textfields-hoverlight-01](https://user-images.githubusercontent.com/3030330/34321067-3d653fd8-e841-11e7-92fc-ea54b3fb9277.gif)
