### ISSUE TITLE
建议涟漪动画效果中涟漪扩散时圆心不要变化。

### ISSUE THREAD

**Issue by a864473066** [zdhxiong/mdui#173]

**Comment by FamioGit** [comment]
建议看看MD设计规范，圆心跟随着用户点击位置

**Comment by TravelingStudent** [comment]
那你入坑Material Design Compents吧，Google官方的框架。
这是演示地址：[戳我前往](http://mdcui.com/demo/ripple.html)

**Comment by DFFZMXJ** [comment]
Ta的意思应该是，涟漪动画的涟漪应该是一个圆扩散应该是以height和width的增加实现，而不是通过缩小与元素的间距的方式实现。
MDUI似乎就是用缩小间距的方式实现的，所以会产生一种涟漪圆心在向中心变化错觉。
个人认为最好的扩散方法是这样的：
```js
//不必写太罗嗦
//变量element代指父元素，ripple代指涟漪元素
var maxRippleRadius = Math.max(element.offsetHeight,element.offsetWidth)*2;//涟漪最大半径
ripple.style.width=ripple.style.height=maxRippleRadius;
```
```css
.mdui-ripple-wave{
    /*在原有MDUI样式上加入此*/
    transition:width,height 235ms linear;
}
```
顺带一提，原生Material Design应用的涟漪好像都是在触摸位置移动或者手抬起后触发的涟漪，而不是触摸后延迟`delay毫秒`触发涟漪。
如果看不懂我说的什么请回复我，我的表达能力确实不佳。有问题也请指出。
