### ISSUE TITLE
文本框帮助文本与字数指示器重合

### ISSUE THREAD

**Issue by DFFZMXJ** [zdhxiong/mdui#252]
这是一个 bug 反馈。
---------------------------
* 使用平台：Windows 10 64位 21H1
* 浏览器及版本：Chromium Edge 91.0.864.59 (64-bit)
* 在线演示：[JS Bin 预览](https://jsbin.com/hutelunaku/edit?html,output)

网络不佳的话，请复制粘贴以下代码：

```html
<div class="mdui-textfield mdui-textfield-floating-label" style="width: 300.5px;"><!--width 值是图中情况下文本框的宽度-->
    <i class="mdui-icon material-icons">location_city</i>
    <label class="mdui-textfield-label">地址</label>
    <input class="mdui-textfield-input" maxlength="60" required>
    <div class="mdui-textfield-error">地址是必须的</div>
    <div class="mdui-textfield-helper">物理地址、IP地址、网址... 是个“地址”就行</div>
</div>
```

### 如何操作

打开网页。

### 预期结果

帮助文本自动换行，避开提示字数的“0/60”，按照 [Material Design 规范](https://www.mdui.org/design/components/text-fields.html#text-fields-layout)。

### 实际结果

帮助文本直接遮盖“0/60”。

**Comment by zdhxiong** [comment]
建议精简文字不要超过一行，非要超过的话自己改点 CSS，比如：
```css
.mdui-textfield {
  overflow: visible;
}

.mdui-textfield-helper {
  overflow: visible;
  white-space: initial;
  text-overflow: initial;
  height: auto;
  padding-right: 48px;
  box-sizing: border-box;
  top: 78px;
}
```

**Comment by DFFZMXJ** [comment]
Many thanks. (\*^▽^\*)

**Comment by DFFZMXJ** [comment]
补充一点，如果输入框是`textarea`，上边的代码会在内容行数较多时出 bug，建议再加点代码：
```css
.mdui-textfield > textarea~.mdui-textfield-helper {
    top: initial;
}
```
