### ISSUE TITLE
为自带边距的组件添加自定义属性，以便添加额外的边距

### ISSUE THREAD

**Issue by Jesse205** [zdhxiong/mdui#289]
比如应用栏
```scss
mdui-top-app-bar {
  // --extra-padding-left: 0px;
  --extra-padding-top: 0px;
  // --extra-padding-right: 0px;
  --extra-padding-bottom: 0px;
  padding-top: calc(var(--extra-padding-top) + var(--extra-padding-bottom) + 0.75rem);
  height: calc(var(--extra-padding-top) + var(--extra-padding-bottom) + 4rem);
  &[variant='medium'] {
    height: calc(var(--extra-padding-top) + var(--extra-padding-bottom) + 7rem);
  }
  &[shrink][variant='large'],
  &[shrink][variant='medium'] {
    height: calc(var(--extra-padding-top) + var(--extra-padding-bottom) + 4rem);
  }
}
```
在需要显示通知栏的时候，可以覆盖`--extra-padding-top`，使内容避开通知栏
![image](https://github.com/zdhxiong/mdui/assets/51242302/e0bf5dc9-5ba5-45a1-a384-f92a41031423)
