### ISSUE TITLE
`mdui-select` should have label CSS Part

### ISSUE THREAD

**Issue by Sduby22** [zdhxiong/mdui#307]
there is color inconsistency when using text-field and select components on non-primary-color background (like a secondary container), because their labels are hardcoded `background-color: rgb(var(--mdui-color-background))`

<img width="239" alt="image" src="https://github.com/zdhxiong/mdui/assets/29040696/89770cd9-e27f-43ae-b77e-2f87b03c8891">

a work-around is to use `::part(label)` to set the background color manually to match background.

```css
    .item::part(label) {
      color: rgb(var(--mdui-color-on-secondary-container));
      background-color: rgb(var(--mdui-color-secondary-container));
    }
```

Unfortunately, `mdui-select` doesn't provide this label CSS part. I have to fallback to `@material/web` implementation.

Interestingly, Google's official implementation is a bit more complex but doesn't have this problem. A brief introduction of Google's implementation is as follows:

<img width="879" alt="image" src="https://github.com/zdhxiong/mdui/assets/29040696/9444560a-d072-4af1-96c5-0e6b510500d7">

Google didn't use a color mask. A text-field / select is divided into 3 parts, when user input something and the label will move to top, with the mid "notch" part's top border disappearing.
