### ISSUE TITLE
dialog的description出现英文会出现滚动条

### ISSUE THREAD

**Issue by huajiqaq** [zdhxiong/mdui#314]
控制台 切换设备为iphone se
mdui.alert({
        headline: "a",
        description: "测试aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa测试",
        confirmText: "a",
});
出现过长的英文不会换行 会出现滚动条
如果全为中文会自动换行
mdui.alert({
        headline: "a",
        description: "测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试",
        confirmText: "a",
});

建议为description的css规则默认加上 word-break:break-all

**Comment by zdhxiong** [comment]
强制断词会导致难以阅读，造成误解。如果你希望强制断词，可以自行修改样式。
```css
mdui-dialog::part(description) {
  word-break: break-all;
}
```
