### ISSUE TITLE
mdui-text-field: label position when field have value

### ISSUE THREAD

**Issue by pointnet** [zdhxiong/mdui#364]
I'm trying to change the overall text-field size using:
```css
mdui-text-field::part(input),
mdui-text-field::part(label),
mdui-text-field::part(container) {
  line-height: var(--mdui-typescale-body-small-line-height);
  font-size: var(--mdui-typescale-body-small-size);
  letter-spacing: var(--mdui-typescale-body-small-tracking);
  font-weight: var(--mdui-typescale-body-small-weight);
}
mdui-text-field::part(input) {
  padding: .5rem .5rem .5rem 0;
}
mdui-text-field::part(container) {
  padding: .125rem .125rem .125rem .875rem;
}
mdui-text-field::part(label) {
  top: .625rem;
}
mdui-text-field[focused]::part(label) {
  top: -.5rem;
}
```

Works pretty well as you can see here on the first empty text-field: [https://codesandbox.io/p/sandbox/friendly-bash-hd7q4n](https://codesandbox.io/p/sandbox/friendly-bash-hd7q4n)

I'm facing an issue with the second text-field where the label is not at the right position when the field have a value.

I can't find a way to override the `:host([variant="outlined"]) .has-value .label` css style of the shadow-root.

Could it be possible to override it as we can for `[focused]` with something like `mdui-text-field[hasvalue]::part(label)` ?
