### ISSUE TITLE
不确定进度指示器的动画不自然 | Indeterminate Preloader is not Material Design-styled at all

### ISSUE THREAD

**Issue by chenyiping1995** [zdhxiong/mdui#82]
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------

在 Documentation 中使用的 “不确定进度条指示器” 动画不够自然，希望能改进。

Google 定义的样式：
https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators

目前 MDUI Documentation 中提供的样式：
https://www.mdui.org/docs/progress/demo1

目前其他 Material Design 框架 (Materialize CSS) 的样式：
http://materializecss.com/preloader.html

**Comment by xbmanh** [comment]
这个网页框架好
http://mdcui.com/demo/linear-progress.html

**Comment by DFFZMXJ** [comment]
从 [Vuetify](https://vuetifyjs.com/en/components/progress-linear/#indeterminate) 搬过来的样式，看看自然不自然。

```css
.mdui-progress-indeterminate::before {
  animation: mdui-progress-optimized 2.2s infinite;
}
.mdui-progress-indeterminate::after {
  animation: mdui-progress-optimized-short 2.2s infinite;
}
@keyframes mdui-progress-optimized {
    0% {
        left: -90%;
        right: 100%
    }

    60% {
        left: -90%;
        right: 100%
    }

    to {
        left: 100%;
        right: -35%
    }
}
@keyframes mdui-progress-optimized-short {
    0% {
        left: -200%;
        right: 100%
    }

    60% {
        left: 107%;
        right: -8%
    }

    to {
        left: 107%;
        right: -8%
    }
}
```
