### ISSUE TITLE
button增加大小设置 目前只有36，增加48 等大小的

### ISSUE THREAD

**Issue by leiqiu** [zdhxiong/mdui#9]

**Comment by zdhxiong** [comment]
规范里并没有48高度的按钮。不过我添加了一个在规范里的密集型按钮，高度是32。
需要其他高度的可以自己加 CSS，例如：
```css
.mdui-btn-lg {
  height: 48px;
  line-height: 48px;
}
```
